<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-P7INNGLR" failures="1" tests="4" name="Default test(failed)" time="0.086" errors="0" timestamp="2024-08-03T10:50:22 IST">
  <testcase classname="testng.RetryTest" name="demo" time="0.022">
    <skipped/>
  </testcase> <!-- demo -->
  <testcase classname="testng.RetryTest" name="demo" time="0.003">
    <skipped/>
  </testcase> <!-- demo -->
  <testcase classname="testng.RetryTest" name="demo" time="0.001">
    <skipped/>
  </testcase> <!-- demo -->
  <testcase classname="testng.RetryTest" name="demo" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testng.RetryTest.demo(RetryTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
</testsuite> <!-- Default test(failed) -->
